name: Challenge 3 IaC
run-name: IaC is running 
on: workflow_dispatch

jobs:
  Azure-Authentication:  
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
