name: Challenge 3 IaC
run-name: IaC is running 
on: workflow_dispatch
env:
  targetEnv: tbl06devops-test

jobs:
  Build-and-deploy-infra:  
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=$targetEnv

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
    
    
